MedicalSystem/MedicalSystem/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from app1 import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    path('admin/', admin.site.urls),
    url(r'^app1/',include('app1.urls')),
    url(r'^logout/$',views.user_logout,name='logout'),
    url(r'special/',views.special,name='special'),
]

MedicalSystem/app1/urls.py
from django.conf.urls import url
from app1 import views

#TEMPLATE URLS!
app_name = 'app1'

urlpatterns = [
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
]

MedicalSystem/app1/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User,on_delete=models.CASCADE)
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

MedicalSystem/app1/forms.py
from django import forms
from django.contrib.auth.models import User
from app1.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

MedicalSystem/app1/views.py
from django.shortcuts import render
from app1.forms import UserProfileInfoForm,UserForm


from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required


# Create your views here.
def index(request):
    return render(request,'app1/index.html')


@login_required
def special(request):
    return HttpResponse("you are logged in, Nice!")


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):

    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors,profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'app1/registration.html',{'user_form':user_form,
                                                    'profile_form':profile_form,
                                                    'registered':registered})

def user_login(request):

    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            print("Someone tried to login and failed ")
            print("Username: {} and password {}".format(username,password) )
            return HttpResponse("invalid login details supplied!")
    else:
        return render(request,'app1/login.html',{})

MedicalSystem/templates/app1/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/css/bootstrap.min.css" integrity="sha384-VCmXjywReHh4PwowAiWNagnWcLhlEJLA5buUprzK8rxFgeH0kww/aWY76TfkUoSX" crossorigin="anonymous"></head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
     <div class="container">
         <ul class="nav navbar-nav">
             <li><a class="navbar-brand" href="{% url 'index' %}">Home</a></li>
             <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
             <li><a class="navbar-link" href="{% url 'app1:register' %}">Register</a></li>
             {% if user.is_authenticated %}
                 <li><a class="navbar-link" href="{% url 'logout' %}">Logout</a></li>
             {% else %}
                 <li><a class="navbar-link" href="{% url 'app1:user_login' %}">Login</a></li>
             {% endif %}

         </ul>
     </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
</body>
</html>

MedicalSystem/templates/app1/index.html
{% extends "app1/base.html" %}
{% block body_block %}

<div class="jumbotron">
    <h1>Django Level Five</h1>
</div>

{% endblock %}

MedicalSystem/templates/app1/login.html
{% extends 'app1/base.html' %}
{% block body_block %}


    <div class="jumbotron">
    <h1>Please Login</h1>
    <form action="{% url 'app1:user_login' %}" method="post">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="Enter Username">

        <label for="password">Password:</label>
        <input type="password" name="password" >

        <input type="submit" name="" value="Login">
    </form>
    </div>
{% endblock %}

MedicalSystem/templates/app1/registration.html
{% extends "app1/base.html" %}
{% load static %}

{% block body_block %}

<div class="jumbotron">
    {% if registered %}
        <h1>Thank you for registering</h1>
    {% else %}
        <h1>Register Here</h1>
        <h3>Fill out the form:</h3>

        <form enctype="multipart/form-data" method="post" >
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <input type="submit" name="" value="Register">
        </form>
    {% endif %}
</div>

{% endblock %}